[template]
name = "test-template"
description = "A simple test template"
language = "rust"

[template.variables]
project_name = { description = "Name of the project", default = "my-project" }
author = { description = "Author name", default = "Your Name" }